export const PERSONAL_INFORMATION = "PERSONAL_INFORMATION";
export const PROFESSIONAL_SUMMARY = "PROFESSIONAL_SUMMARY";
export const EXPERIENCE = "EXPERIENCE";
export const EDUCATION = "EDUCATION";
export const PROJECTS = "PROJECTS";
export const SKILL = "SKILL";
export const SOCIAL_LINK = "SOCIAL_LINK";

export const MESSAGE='MESSAGE'

export const AUTH_CHECK_STATE = "AUTH_CHECK_STATE";
export const AUTH_USER = "AUTH_USER";

export const GOOGLE_AUTH_SUCCESS = "GOOGLE_AUTH_SUCCESS";
export const GOOGLE_AUTH_FAIL = "GOOGLE_AUTH_FAIL";

export const SESSION_TOKEN_START = "SESSION_TOKEN_START";
export const SESSION_TOKEN_SUCCESS = "SESSION_TOKEN_SUCCESS";
export const SESSION_TOKEN_FAIL = "SESSION_TOKEN_FAIL";

export const AUTH_CHECK_TIMEOUT = "AUTH_CHECK_TIMEOUT";
export const AUTH_INITIATE_LOGOUT = "AUTH_INITIATE_LOGOUT";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";
