export const PERSONAL_INFORMATION='PERSONAL_INFORMATION'
export const EXPERIENCE='EXPERIENCE'
export const EDUCATION='EDUCATION'
export const PROJECTS='PROJECTS'
export const SKILL='SKILL'
export const SOCIAL_LINK='SOCIAL_LINK'

export const AVATAR_UPLOAD='AVATAR_UPLOAD'
export const AVATAR_UPLOAD_FAILED='AVATAR_UPLOAD_FAILED'
