// Edit actions
export const FETCH_PORTFOLIO='FETCH_PORTFOLIO';
export const PERSONAL_INFORMATION='PERSONAL_INFORMATION';
export const EXPERIENCE='EXPERIENCE';
export const EDUCATION='EDUCATION';
export const PROJECTS='PROJECTS';
export const SKILL='SKILL';

export const ADD_SOCIAL_LINK='ADD_SOCIAL_LINK';
export const EDIT_SOCIAL_LINK='EDIT_SOCIAL_LINK';
export const DELETE_SOCIAL_LINK='DELETE_SOCIAL_LINK';

export const AVATAR_UPLOAD='AVATAR_UPLOAD';
export const AVATAR_UPLOAD_FAILED='AVATAR_UPLOAD_FAILED';

export const MESSAGES='MESSAGES';

export const AUTH_CHECK_STATE = "AUTH_CHECK_STATE";
export const AUTH_USER = "AUTH_USER";

export const GOOGLE_AUTH_START = "GOOGLE_AUTH_START";
export const GOOGLE_AUTH_SUCCESS = "GOOGLE_AUTH_SUCCESS";
export const GOOGLE_AUTH_FAIL = "GOOGLE_AUTH_FAIL";

export const SESSION_TOKEN_SUCCESS = "SESSION_TOKEN_SUCCESS";
export const SESSION_TOKEN_FAIL = "SESSION_TOKEN_FAIL";
export const RESET_ERROR = "RESET_ERROR";

export const AUTH_CHECK_TIMEOUT = "AUTH_CHECK_TIMEOUT";
export const AUTH_INITIATE_LOGOUT = "AUTH_INITIATE_LOGOUT";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";

export const ADD_EDUCATION='ADD_EDUCATION';
export const DELETE_EDUCATION='DELETE_EDUCATION';
export const EDIT_EDUCATION='EDIT_EDUCATION';

export const ADD_EXPERIENCE='ADD_EXPERIENCE';
export const DELETE_EXPERIENCE='DELETE_EXPERIENCE';
export const EDIT_EXPERIENCE='EDIT_EXPERIENCE';

export const ADD_PORJECT='ADD_PROJECT'
export const DELETE_PROJECT='DELETE_PROJECT'
export const EDIT_PROJECT='EDIT_PROJECT'

export const EDIT_SKILL='EDIT_SKILL'
export const DELETE_SKILL='DELETE_SKILL'

export const SUBSKILL='SUBSKILL'
export const DELETE_SUBSKILL='DELETE_SUBSKILL'

